version: "3"
networks:
  cocoannotator:
    external: false

services:
  webserver:
    container_name: annotator_webserver
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver2:
    container_name: annotator_webserver2
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5001:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver2:
    container_name: annotator_webserver2
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5001:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver3:
    container_name: annotator_webserver3
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5002:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver4:
    container_name: annotator_webserver4
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5003:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver5:
    container_name: annotator_webserver5
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5004:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver6:
    container_name: annotator_webserver6
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5005:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver7:
    container_name: annotator_webserver7
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5006:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver8:
    container_name: annotator_webserver8
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5007:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=production
      - DEBUG=false
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  workers:
    container_name: annotator_workers
    build:
      context: .
      dockerfile: ./backend/workers/Dockerfile
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    ports:
      - 5555:5555
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    networks:
      - cocoannotator